"""
Export API
AI SINTA
"""

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse
from pydantic import BaseModel

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
)
from reportlab.lib.styles import getSampleStyleSheet

from datetime import datetime
import os
import json
import csv

from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT

from openpyxl import Workbook
from openpyxl.styles import (
    Font,
    PatternFill,
    Alignment,
    Border,
    Side,
)
from openpyxl.utils import get_column_letter

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
)
from reportlab.lib.styles import getSampleStyleSheet


router = APIRouter(
    prefix="/export",
    tags=["Export"]
)

EXPORT_FOLDER = "exports"

os.makedirs(
    EXPORT_FOLDER,
    exist_ok=True
)


# =====================================================
# MODEL
# =====================================================

class ExportRequest(BaseModel):
    question: str
    answer: str
    format: str = "pdf"

# =====================================================
# PDF
# =====================================================

def export_pdf(question, answer):

    filename = f"chat_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    filepath = os.path.join(EXPORT_FOLDER, filename)

    styles = getSampleStyleSheet()

    doc = SimpleDocTemplate(
        filepath,
        pagesize=A4,
        rightMargin=1.5 * cm,
        leftMargin=1.5 * cm,
        topMargin=1.5 * cm,
        bottomMargin=1.5 * cm,
    )

    body = styles["BodyText"]
    body.fontSize = 9
    body.leading = 12

    story = [
        Paragraph("<b>AI SINTA</b>", styles["Heading1"]),
        Paragraph("<b>Pertanyaan</b>", styles["Heading2"]),
        Paragraph(question, body),
        Spacer(1, 10),
        Paragraph("<b>Jawaban</b>", styles["Heading2"]),
    ]

    for line in answer.split("\n"):
        line = line.strip()

        if not line:
            story.append(Spacer(1, 6))
        else:
            story.append(Paragraph(line, body))

    story.append(Spacer(1, 10))
    story.append(
        Paragraph(
            datetime.now().strftime("%d-%m-%Y %H:%M:%S"),
            styles["Italic"],
        )
    )

    doc.build(story)

    return filepath


# =====================================================
# WORD
# =====================================================

def export_word(question, answer):

    filename = f"chat_{datetime.now().strftime('%Y%m%d_%H%M%S')}.docx"
    filepath = os.path.join(EXPORT_FOLDER, filename)

    doc = Document()

    title = doc.add_heading("AI SINTA", level=1)
    title.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

    subtitle = doc.add_paragraph("Asisten Informasi Kebencanaan SITABA")
    subtitle.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER

    doc.add_paragraph()

    doc.add_heading("Pertanyaan", level=2)
    p = doc.add_paragraph()
    run = p.add_run(question)
    run.font.size = Pt(10)

    doc.add_paragraph()

    doc.add_heading("Jawaban AI", level=2)

    for line in answer.split("\n"):
        line = line.strip()

        if not line:
            continue

        if line.startswith("•"):
            p = doc.add_paragraph(style="List Bullet")
            p.add_run(line.replace("•", "").strip())
        else:
            p = doc.add_paragraph()
            run = p.add_run(line)
            run.font.size = Pt(10)

    doc.add_paragraph()

    footer = doc.add_paragraph()
    footer.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
    run = footer.add_run(
        "Generated by AI SINTA - Kementerian PU | "
        + datetime.now().strftime("%d-%m-%Y %H:%M:%S")
    )
    run.italic = True
    run.font.size = Pt(9)

    doc.save(filepath)

    return filepath


# =====================================================
# EXCEL
# =====================================================

def export_excel(question, answer):

    filename = f"chat_{datetime.now().strftime('%Y%m%d_%H%M%S')}.xlsx"
    filepath = os.path.join(EXPORT_FOLDER, filename)

    wb = Workbook()
    ws = wb.active
    ws.title = "AI SINTA"

    blue_fill = PatternFill("solid", fgColor="1F4E78")
    light_fill = PatternFill("solid", fgColor="D9EAF7")
    white_font = Font(color="FFFFFF", bold=True)
    bold_font = Font(bold=True)
    thin = Side(border_style="thin", color="D9D9D9")
    border = Border(left=thin, right=thin, top=thin, bottom=thin)

    ws.merge_cells("A1:D1")
    ws["A1"] = "LAPORAN AI SINTA"
    ws["A1"].font = Font(size=16, bold=True, color="FFFFFF")
    ws["A1"].fill = blue_fill
    ws["A1"].alignment = Alignment(horizontal="center")

    ws["A3"] = "Pertanyaan"
    ws["B3"] = question
    ws["A4"] = "Tanggal Export"
    ws["B4"] = datetime.now().strftime("%d-%m-%Y %H:%M:%S")

    for cell in ["A3", "A4"]:
        ws[cell].font = bold_font
        ws[cell].fill = light_fill

    headers = ["No", "Kategori", "Isi Jawaban", "Keterangan"]
    ws.append([])
    ws.append(headers)

    header_row = 6

    for col in range(1, 5):
        cell = ws.cell(row=header_row, column=col)
        cell.font = white_font
        cell.fill = blue_fill
        cell.alignment = Alignment(horizontal="center")
        cell.border = border

    lines = [line.strip() for line in answer.split("\n") if line.strip()]

    row = 7
    no = 1

    for line in lines:
        kategori = "Isi"

        if line.startswith("📍"):
            kategori = "Judul"
        elif line.startswith("📌") or line.startswith("🗺") or line.startswith("🏙") or line.startswith("🚧") or line.startswith("🏚") or line.startswith("🛣") or line.startswith("📋"):
            kategori = "Bagian"
        elif line.startswith("•"):
            kategori = "Poin"
        elif line[:2].replace(".", "").isdigit():
            kategori = "Detail"

        ws.cell(row=row, column=1, value=no)
        ws.cell(row=row, column=2, value=kategori)
        ws.cell(row=row, column=3, value=line)
        ws.cell(row=row, column=4, value="")

        for col in range(1, 5):
            cell = ws.cell(row=row, column=col)
            cell.border = border
            cell.alignment = Alignment(vertical="top", wrap_text=True)

        if kategori in ["Judul", "Bagian"]:
            for col in range(1, 5):
                ws.cell(row=row, column=col).fill = light_fill
                ws.cell(row=row, column=col).font = bold_font

        row += 1
        no += 1

    ws.column_dimensions["A"].width = 8
    ws.column_dimensions["B"].width = 18
    ws.column_dimensions["C"].width = 90
    ws.column_dimensions["D"].width = 25

    ws.freeze_panes = "A7"
    ws.auto_filter.ref = f"A6:D{row-1}"

    wb.save(filepath)

    return filepath


# =====================================================
# CSV
# =====================================================

def export_csv(question, answer):

    filename = f"chat_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv"
    filepath = os.path.join(EXPORT_FOLDER, filename)

    lines = [line.strip() for line in answer.split("\n") if line.strip()]

    with open(
        filepath,
        "w",
        newline="",
        encoding="utf-8-sig"
    ) as f:

        writer = csv.writer(f, delimiter=";")

        writer.writerow([
            "No",
            "Pertanyaan",
            "Isi Jawaban",
            "Tanggal"
        ])

        for i, line in enumerate(lines, start=1):
            writer.writerow([
                i,
                question if i == 1 else "",
                line,
                datetime.now().strftime("%d-%m-%Y %H:%M:%S") if i == 1 else ""
            ])

    return filepath


# =====================================================
# TXT
# =====================================================

def export_txt(question, answer):

    filename = f"chat_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"
    filepath = os.path.join(EXPORT_FOLDER, filename)

    created_at = datetime.now().strftime("%d-%m-%Y %H:%M:%S")

    with open(filepath, "w", encoding="utf-8") as f:
        f.write("AI SINTA - LAPORAN HASIL CHAT\n")
        f.write("=" * 60)
        f.write("\n\n")

        f.write("PERTANYAAN\n")
        f.write("-" * 60)
        f.write("\n")
        f.write(question.strip())
        f.write("\n\n")

        f.write("JAWABAN\n")
        f.write("-" * 60)
        f.write("\n")

        for line in answer.split("\n"):
            line = line.strip()
            if line:
                f.write(line + "\n")
            else:
                f.write("\n")

        f.write("\n")
        f.write("=" * 60)
        f.write("\n")
        f.write(f"Generated by AI SINTA - Kementerian PU\n")
        f.write(f"Tanggal Export: {created_at}\n")

    return filepath


# =====================================================
# JSON
# =====================================================

def export_json(question, answer):

    filename = f"chat_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    filepath = os.path.join(EXPORT_FOLDER, filename)

    created_at = datetime.now().isoformat()

    data = {
        "app": "AI SINTA",
        "source": "SITABA Kementerian PU",
        "created_at": created_at,
        "question": question.strip(),
        "answer": answer.strip(),
        "answer_lines": [
            line.strip()
            for line in answer.split("\n")
            if line.strip()
        ],
        "metadata": {
            "format": "json",
            "generated_by": "AI SINTA",
            "institution": "Kementerian PU"
        }
    }

    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=4, ensure_ascii=False)

    return filepath


# =====================================================
# EXPORT
# =====================================================

@router.post("/")
def export_chat(data: ExportRequest):

    format = data.format.lower()

    if format == "pdf":

        path = export_pdf(
            data.question,
            data.answer
        )

    elif format == "docx":

        path = export_word(
            data.question,
            data.answer
        )

    elif format == "xlsx":

        path = export_excel(
            data.question,
            data.answer
        )

    elif format == "csv":

        path = export_csv(
            data.question,
            data.answer
        )

    elif format == "txt":

        path = export_txt(
            data.question,
            data.answer
        )

    elif format == "json":

        path = export_json(
            data.question,
            data.answer
        )

    else:

        raise HTTPException(
            status_code=400,
            detail="Format export tidak didukung."
        )

    return {

        "success": True,

        "message": "Export berhasil.",

        "file": os.path.basename(path),

        "download": f"/export/download/{os.path.basename(path)}"

    }


# =====================================================
# DOWNLOAD
# =====================================================

@router.get("/download/{filename}")
def download_file(filename: str):

    filepath = os.path.join(
        EXPORT_FOLDER,
        filename
    )

    if not os.path.exists(filepath):

        raise HTTPException(
            status_code=404,
            detail="File tidak ditemukan."
        )

    return FileResponse(
        filepath,
        filename=filename
    )


# =====================================================
# LIST FILE
# =====================================================

@router.get("/files")
def list_export():

    files = []

    for file in os.listdir(EXPORT_FOLDER):

        files.append({

            "filename": file,

            "download": f"/export/download/{file}"

        })

    return {

        "success": True,

        "total": len(files),

        "files": files

    }


# =====================================================
# DELETE FILE
# =====================================================

@router.delete("/{filename}")
def delete_export(filename: str):

    filepath = os.path.join(
        EXPORT_FOLDER,
        filename
    )

    if not os.path.exists(filepath):

        raise HTTPException(
            status_code=404,
            detail="File tidak ditemukan."
        )

    os.remove(filepath)

    return {

        "success": True,

        "message": "File berhasil dihapus."

    }